### ISSUE TITLE
Duration of train ride incorrect

### ISSUE THREAD

**Issue by bdvrieze** [Jan-Bart/MMM-NMBS-Connection#3]
![50fbe2ef-d7b8-4ed4-93c0-3ec0af9bdbef](https://user-images.githubusercontent.com/17237379/45813252-6648c800-bcd2-11e8-880a-14386a82d2fc.png)

As you ca see the duration of the ride is always one hour and not the correct time.
This could be by design (these trains always run late 😉) but I don't think that it's meant this way.

Feature request (alas I can't code): it would be nice to have the name of the station under departure and arrival.

Again many thx for this module!

**Comment by Jan-Bart** [comment]
Hi @bdvrieze,

Because of the "[humanize](https://momentjs.com/docs/#/durations/humanize/)" function in moment.js duration times are rounded.

So, 46 minutes are rounded to the next full hour (1 hour)
I could make this optional, so you can see the exact minutes as well.

I'll have a look to put the name of the station beneath departure and arrival.

**Comment by Jan-Bart** [comment]
@bdvrieze 
Both issues should be fixed now.

You can add it in config:

```
  config: {
    humanizeDuration: false,
    showStationNames: true,
  }
```

**Comment by bdvrieze** [comment]
I'll try it out ASAP :)

Thanks!

**Comment by bdvrieze** [comment]
Works like a charm thanks!
